#!/bin/bash
eye "$@" --tactic limited-answer 1 --n3 http://josd.github.io/eye/i/dpe/dpe_theory.n3 --n3 http://josd.github.io/eye/i/dpe/dpe_assumption.n3 --query http://josd.github.io/eye/i/dpe/dpe_query.n3 > dpe_proof.n3
