#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/programming/nbbn/nbbn-plugin.n3 --n3 http://josd.github.io/eye/programming/nbbn/nbbn-model.n3 --query http://josd.github.io/eye/programming/nbbn/nbbn-query.n3 > nbbn_proof.n3
