#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/eyereasoning/mmln/mmln-gv-example.n3 --n3 http://josd.github.io/eye/eyereasoning/mmln/mmln-gv-mln.n3 --n3 http://josd.github.io/eye/eyereasoning/mmln/mmln-plugin.n3 --query http://josd.github.io/eye/eyereasoning/mmln/mmln-gv-query.n3 > mmln-gv-proof.n3
