#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/inferencing/pptbank/bankSW.n3 --n3 http://josd.github.io/eye/inferencing/pptbank/checking.n3 --query http://josd.github.io/eye/inferencing/pptbank/query.n3 > proof.n3
