#!/bin/bash
eye "$@" --nope --n3 palindrome.n3 palindrome-declarations.n3 --n3 preduction-plugin.n3 --query palindrome-preduction.n3 > palindrome2.n3
eye "$@" --n3 http://josd.github.io/eye/eyereasoning/preduction/palindrome.n3 --query http://josd.github.io/eye/eyereasoning/preduction/palindrome-query.n3 > palindrome-proof.n3
eye "$@" --n3 http://josd.github.io/eye/eyereasoning/preduction/palindrome2.n3 --query http://josd.github.io/eye/eyereasoning/preduction/palindrome2-query.n3 > palindrome2-proof.n3
eye "$@" --nope --n3 food.n3 food-declarations.n3 --n3 preduction-plugin.n3 --query food-preduction.n3 > food2.n3
eye "$@" --n3 http://josd.github.io/eye/eyereasoning/preduction/food-example.n3 --n3 http://josd.github.io/eye/eyereasoning/preduction/food.n3 --n3 http://josd.github.io/eye/eyereasoning/rpo/rdfs-subClassOf.n3 --query http://josd.github.io/eye/eyereasoning/preduction/food-query.n3 > food-proof.n3
eye "$@" --n3 http://josd.github.io/eye/eyereasoning/preduction/food-example.n3 --n3 http://josd.github.io/eye/eyereasoning/preduction/food2.n3 --query http://josd.github.io/eye/eyereasoning/preduction/food-query.n3 > food2-proof.n3
