#!/bin/bash
eye "$@" --turtle http://josd.github.io/eye/inferencing/cs/data-001.n3 --n3 http://josd.github.io/eye/inferencing/cs/rules-001.n3 --query http://josd.github.io/eye/inferencing/cs/query-001.n3 > proof-001.n3
