#!/bin/bash
eye "$@" --n3p http://josd.github.io/eye/eyereasoning/n3p/simple.ttl > simple.n3p
eye "$@" --n3p http://josd.github.io/eye/eyereasoning/n3p/extra.ttl > extra.n3p
eye "$@" --n3p http://josd.github.io/eye/eyereasoning/n3p/literals.ttl > literals.n3p
eye "$@" --n3p http://josd.github.io/eye/eyereasoning/n3p/sample.n3 > sample.n3p
