#!/bin/bash
eye "$@" --tactic limited-answer 1 --n3 http://josd.github.io/eye/eyereasoning/restpath/initial.n3 --n3 http://josd.github.io/eye/eyereasoning/restpath/path-9-3.n3 --query http://josd.github.io/eye/eyereasoning/restpath/goal.n3 > path-9-3-proof.n3
