#!/bin/bash
eye "$@" --nope --n3 http://josd.github.io/eye/book/swet/swetA.n3 --n3 http://josd.github.io/eye/book/swet/swetD.n3 --query=http://josd.github.io/eye/book/swet/swetQ01.n3 > swetA01.n3
eye "$@" --nope --n3 http://josd.github.io/eye/book/swet/swetA.n3 --n3 http://josd.github.io/eye/book/swet/swetD.n3 --query=http://josd.github.io/eye/book/swet/swetQ11.n3 > swetA11.n3
eye "$@" --nope --n3 http://josd.github.io/eye/book/swet/swetA.n3 --n3 http://josd.github.io/eye/book/swet/swetD.n3 --query=http://josd.github.io/eye/book/swet/swetQ21.n3 > swetA21.n3
eye "$@" --nope --n3 http://josd.github.io/eye/book/swet/swetA.n3 --n3 http://josd.github.io/eye/book/swet/swetD.n3 --query=http://josd.github.io/eye/book/swet/swetQ31.n3 > swetA31.n3

eye "$@" --n3 http://josd.github.io/eye/book/swet/swetA.n3 --query=http://josd.github.io/eye/book/swet/swetQ.n3 > swet_proof.n3
