#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/eyereasoning/fcm/fcm-plugin.n3 --n3 http://josd.github.io/eye/eyereasoning/fcm/fl-rules.n3 --n3 http://josd.github.io/eye/eyereasoning/fcm/example001P.n3 --n3 http://josd.github.io/eye/eyereasoning/fcm/example002P.n3 --query http://josd.github.io/eye/eyereasoning/fcm/example003Q.n3 > fcm_proof.n3
