#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/i/rpo/food-example.n3 --n3 http://josd.github.io/eye/i/rpo/food.n3 --n3 http://josd.github.io/eye/i/rpo/rdfs-subClassOf.n3 --query http://josd.github.io/eye/i/rpo/food-query.n3 > food-proof.n3
