#!/bin/bash

function swap {
   eye.py http://josd.github.io/eye/swap/graph.n3
   eye.py http://josd.github.io/eye/swap/grapht.n3
   eye.py http://josd.github.io/eye/swap/list.n3
   eye.py http://josd.github.io/eye/swap/socrates.n3
   eye.py http://josd.github.io/eye/swap/tree.n3
   eye.py http://josd.github.io/eye/swap/einstein.n3
   eye.py http://josd.github.io/eye/swap/xanthippe.n3
   eye.py http://www.agfa.com/w3c/euler/example003P.n3
   eye.py http://www.agfa.com/w3c/euler/medI.n3
}

swap "$@" |& tee swap.txt
