#!/bin/bash
curl -s -L http://josd.github.io/eye/eyereasoning/streason/graph-10.n3 | eye "$@" --nope --n3 http://josd.github.io/eye/eyereasoning/streason/streason-rules.n3 --turtle - --streaming-reasoning > streason-output.n3
