#!/bin/bash
eye "$@" --no-distinct-output --nope --n3 sdcoding.n3 --query sdcoding-q.n3 > sdcoding-a.n3
eye "$@" --no-distinct-input --nope --n3 sdcoding-a.n3 --query sdcoding-query.n3 > sdcoding-answer.n3
