#!/bin/bash
eye "$@" --turtle http://josd.github.io/eye/i2i/csv/select-data.n3 --query http://josd.github.io/eye/i2i/csv/select-query.n3 > select-proof.n3
eye "$@" --n3 http://josd.github.io/eye/i2i/csv/select-data-extra.n3 --query http://josd.github.io/eye/i2i/csv/select-query.n3 > select-proof-extra.n3
