#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/i2i/gedcom/gedcom-facts.n3 --n3 http://josd.github.io/eye/i2i/gedcom/gedcom-relations.n3 --n3 http://josd.github.io/eye/i2i/gedcom/rpo-rules.n3 --query http://josd.github.io/eye/i2i/gedcom/gedcom-filter.n3 > gedcom-proof.n3
