#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/inferencing/graph/graph.axiom.n3 --n3 http://josd.github.io/eye/inferencing/graph/rpo-rules.n3 --query http://josd.github.io/eye/inferencing/graph/graph.filter.n3 > graph.proof.n3
