#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/i2i/dt/test-facts.n3 --n3 http://josd.github.io/eye/i2i/dt/test-dt-1000.n3 --query http://josd.github.io/eye/i2i/dt/test-query.n3 > test-proof-1000.n3
