#!/bin/bash
curl -s -L http://josd.github.io/eye/inferencing/streason/graph-10.n3 | eye "$@" --nope --n3 http://josd.github.io/eye/inferencing/streason/streason-rules.n3 --turtle - --streaming-reasoning > streason-output.n3
