#!/bin/bash
eye "$@" --n3 http://josd.github.io/eye/book/image/year.n3 --n3 http://josd.github.io/eye/book/image/easter.n3 --image ype.pvm
swipl -x ype.pvm -- "$@" --query http://josd.github.io/eye/book/image/query.n3 > easter-proof.n3
